# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

resources:
  repositories:
  - repository: DemoRepo
    type: github
    endpoint: nevillejrbrown
    name: nevillejrbrown/demo
  
  - repository: DemoTestRepo
    type: github
    endpoint: nevillejrbrown
    name: nevillejrbrown/DemoTest

  - repository: UITestRepo
    type: github
    endpoint: nevillejrbrown
    name: nevillejrbrown/DemoUITests

steps:
- checkout: DemoRepo
- checkout: DemoTestRepo
- checkout: UITestRepo


- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/DemoTest/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

# this code takes all the files in $(Build.ArtifactStagingDirectory) and uploads them as an artifact of your build.
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'DemoSite' 


- task: AzureWebApp@1
  inputs:
    azureSubscription: 'DemoWebAppServiceConnection'
    appType: webApp
    appName: 'NevillejrbrownDemoApp'
    package: $(Build.ArtifactStagingDirectory)/demo.zip 